
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setTitle("Control de Excepciones");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        btnControlar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(radio1);
        radio1.setText("ArithmeticException");

        buttonGroup1.add(radio2);
        radio2.setText("NumberFormatException");

        buttonGroup1.add(radio3);
        radio3.setText("IOException");

        buttonGroup1.add(radio4);
        radio4.setText("ArrayIndexOutOfBoundsException");

        btnControlar.setText("Controlar Excepción");
        btnControlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio2)
                            .addComponent(radio3)
                            .addComponent(radio4)
                            .addComponent(radio1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnControlar)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(radio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio4)
                .addGap(18, 18, 18)
                .addComponent(btnControlar)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnControlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlarActionPerformed
        if(radio1.isSelected()) {
            this.ctrl_Exp1();
        }
        else if(radio2.isSelected()) {
            this.ctrl_Exp2();
        }
        else if(radio3.isSelected()) {
            this.ctrl_Exp3();
        }
        else if(radio4.isSelected()) {
            this.ctrl_Exp4();
        }
        else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún radioButton");
        }
            
    }//GEN-LAST:event_btnControlarActionPerformed

    private void ctrl_Exp1() {
        try {
            JOptionPane.showMessageDialog(this, "Division por cero: 5/0", "Aviso Inicial", JOptionPane.INFORMATION_MESSAGE);
            int a = 5 / 0;
        } catch (ArithmeticException err) {
            JOptionPane.showMessageDialog(this, "Entramos en la excepcion: a=0", "Aviso Excepcion", JOptionPane.WARNING_MESSAGE);
            int a = 0;
        }
    }

    private void ctrl_Exp2() {
        try {
            JOptionPane.showMessageDialog(this, "Formato no entero: a=Hola", "Aviso Inicial", JOptionPane.INFORMATION_MESSAGE);
            int a = Integer.parseInt("Hola");
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(this, "Entramos en la excepcion: a=0", "Aviso Excepcion", JOptionPane.WARNING_MESSAGE);
            int a = 0;
        } finally {
            JOptionPane.showMessageDialog(this, "Se ejecuta despues del bloque try se produzca excepcion o no", "Aviso Finally", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void ctrl_Exp3() {
        JOptionPane.showMessageDialog(this, "Lectura de fichero", "Aviso Inicial", JOptionPane.INFORMATION_MESSAGE);
        try (FileReader lector = new FileReader("archivo.txt")) {
            int i = 0;
            while (i != -1) {
                i = lector.read();
                // System.out.println((char) i);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el fichero", "Aviso Excepcion", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void ctrl_Exp4() {
        JOptionPane.showMessageDialog(this, "Array fuera de rango", "Aviso Inicial", JOptionPane.INFORMATION_MESSAGE);
        int lista[] = new int[3];
        try {
            lista[5] = 10;
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "Error: Posicion no valida.", "Aviso Excepcion", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnControlar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    // End of variables declaration//GEN-END:variables
}
